### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by antzor10** [cseagle/fREedom#2]
When i try  to disassemble a simple Hello world! program, it not work.

Created section .text, 0x401000:0x401420, raw length 0x600, perms 5
Created section .rdata, 0x402000:0x40228e, raw length 0x400, perms 1
Created section .data, 0x403000:0x403108, raw length 0x200, perms 3
Traceback (most recent call last):
  File "fREedom.py", line 89, in <module>
    main(args)
  File "fREedom.py", line 51, in main
    dis.generate_data()
  File "/home/tony/binnavi/free/bn_disasm.py", line 604, in generate_data
    self.generate_disassembly()
  File "/home/tony/binnavi/free/bn_disasm.py", line 585, in generate_disassembly
    self.process_operands(i)
  File "/home/tony/binnavi/free/x86_disasm.py", line 271, in process_operands
    op_size = 'b%d' % op.size
AttributeError: 'X86Op' object has no attribute 'size'

**Comment by cseagle** [comment]
Do you mind sending the source for your program? Also what platform was it
built gor and what compiler did you use?

Chris

**Comment by antzor10** [comment]
I use Anjuta IDE. x86 32 bit
[main.cc.zip](https://github.com/cseagle/fREedom/files/75881/main.cc.zip)
[proto.zip](https://github.com/cseagle/fREedom/files/75880/proto.zip)

**Comment by cseagle** [comment]
I have no problems with the proto binary linked below.

python fREedom.py --database binnavi --user binnavi --pass binnavi --dbhost 127.0.0.1 --binary proto
Skipping section 
Created section .interp, 0x8048134:0x8048147, raw length 0x13, perms 1
Created section .note.ABI-tag, 0x8048148:0x8048168, raw length 0x20, perms 1
Created section .note.gnu.build-id, 0x8048168:0x804818c, raw length 0x24, perms 1
Created section .gnu.hash, 0x804818c:0x80481b8, raw length 0x2c, perms 1
Created section .dynsym, 0x80481b8:0x8048288, raw length 0xd0, perms 1
Created section .dynstr, 0x8048288:0x8048410, raw length 0x188, perms 1
Created section .gnu.version, 0x8048410:0x804842a, raw length 0x1a, perms 1
Created section .gnu.version_r, 0x804842c:0x804847c, raw length 0x50, perms 1
Created section .rel.dyn, 0x804847c:0x804848c, raw length 0x10, perms 1
Created section .rel.plt, 0x804848c:0x80484c4, raw length 0x38, perms 1
Created section .init, 0x80484c4:0x80484e7, raw length 0x23, perms 5
Created section .plt, 0x80484f0:0x8048570, raw length 0x80, perms 5
Created section .text, 0x8048570:0x8048742, raw length 0x1d2, perms 5
Created section .fini, 0x8048744:0x8048758, raw length 0x14, perms 5
Created section .rodata, 0x8048758:0x804876d, raw length 0x15, perms 1
Created section .eh_frame_hdr, 0x8048770:0x80487a4, raw length 0x34, perms 1
Created section .eh_frame, 0x80487a4:0x8048888, raw length 0xe4, perms 1
Created section .init_array, 0x8049888:0x8049890, raw length 0x8, perms 3
Created section .fini_array, 0x8049890:0x8049894, raw length 0x4, perms 3
Created section .jcr, 0x8049894:0x8049898, raw length 0x4, perms 3
Created section .dynamic, 0x8049898:0x8049998, raw length 0x100, perms 3
Created section .got, 0x8049998:0x804999c, raw length 0x4, perms 3
Created section .got.plt, 0x804999c:0x80499c4, raw length 0x28, perms 3
Created section .data, 0x80499c4:0x80499cc, raw length 0x8, perms 3
Created section .bss, 0x8049a00:0x8049a90, raw length 0x90, perms 3
Skipping section .comment
Skipping section .shstrtab
After first pass, have 40 insts
found 40 instructions
found 9 basic blocks
found 7 functions
add_sections
add_types
add_operands
add_instructions
add_functions
add_basic_blocks
add_nodes
add_trees
add_tree_nodes

Chris
