### ISSUE TITLE
List index out of range on bn_disasm.py, line 396

### ISSUE THREAD

**Issue by roj4s** [cseagle/fREedom#5]
Hi, i think this project is a great idea. I've been trying to use it with many pe32 and .exe without success yet on a single file. All i get is the error:
     Traceback (most recent call last):
  File "fREedom.py", line 93, in <module>
    main(args)
  File "fREedom.py", line 55, in main
    dis.generate_data()
  File "bn_disasm.py", line 638, in generate_data
    self.set_basic_block_instructions()
  File "bn_disasm.py", line 396, in set_basic_block_instructions
    addr = xrefs[0][0]
IndexError: list index out of range
Any advice is apreciated. Thanks in advance.

**Comment by cseagle** [comment]
Can you share a PE that exhibits this problem? Or, tell me a standard
windows binary that does. calc.exe or notepad.exe for example.

**Comment by roj4s** [comment]
Hi, thanks for the quick answer. I've shared some samples here: https://goo.gl/tJ3QZX 
I will try with a standard windows binary in a minute.

**Comment by cseagle** [comment]
Thanks for the links. I'll take a look next time I'm at my computer.

**Comment by roj4s** [comment]
Now i've tryed with the windows ten calculator and notepad executables without success.  Already included it on the shared samples at: https://goo.gl/tJ3QZX. Thanks.

**Comment by cseagle** [comment]
I pushed a fix for this. Please let me know if you have any other problems.
