### ISSUE TITLE
not stripped ELF64 bin

### ISSUE THREAD

**Issue by ghost** [cseagle/fREedom#7]
Traceback (most recent call last):
  File "./fREedom.py", line 93, in <module>
    main(args)
  File "./fREedom.py", line 46, in main
    if not ldr.load():
  File "fREedom/elf_loader.py", line 747, in load
    self.parse_symbols()
  File "fREedom/elf_loader.py", line 668, in parse_symbols
    name = self.get_string(self.symbol_strtab + st_name)
  File "fREedom/loader.py", line 194, in get_string
    res += ch
TypeError: cannot concatenate 'str' and 'NoneType' objects

the problem is here: https://github.com/cseagle/fREedom/blob/master/loader.py#L194
because get_byte() returns a None object.

**Comment by n0way0ut** [comment]
I tried to patch it. shstrtab and strtab sections contain also a NULL string symbol. just skip it.

diff --git a/elf_loader.py b/elf_loader.py
index 9b485e9..06c73d4 100755
--- a/elf_loader.py
+++ b/elf_loader.py
@@ -653,6 +653,8 @@ class ElfBase(Loader):
             #print "Section %s has %d symbols" % (s.name, num_syms)
             for i in range(num_syms):
                addr = s.sh_addr + i * symsz
+               if addr == 0:
+                  break
                st_name = self.get_dword(addr)
                if self.sizeof_ptr == 4:
                   idx = 2
diff --git a/fREedom.py b/fREedom.py
index aeb4d17..f54a216 100755
--- a/fREedom.py
+++ b/fREedom.py
@@ -65,10 +65,10 @@ def main(args):
       print "   0x%x" % c
    '''
 
-   #dis.print_disassembly()
+   dis.print_disassembly()
 
-   db = binnavi_db.binnavi_db(args.database, args.user, args.passwd, args.dbhost)
-   db.export(dis)
+   #db = binnavi_db.binnavi_db(args.database, args.user, args.passwd, args.dbhost)
+   #db.export(dis)
 
 # add argument parsing for database commection parameters
 if __name__ == "__main__":
diff --git a/loader.py b/loader.py
index e457e00..f9204c3 100755
--- a/loader.py
+++ b/loader.py
@@ -188,7 +188,7 @@ class Loader(object):
       res = ''
       while True:
          ch = self.get_byte(addr)
-         if ch == '\x00':
+         if ch == '\x00' or ch == None:
             break
          addr += 1
          res += ch

**Comment by cseagle** [comment]
Should be fixed with commit 49dda0d
